name: 'Haechi'
description: 'Rectifying the Korean Wave'
meta_description: 'Morning Calm ...'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'haechi.me'
google_analytics: 'UA-65232017-1'

# Details for the RSS feed generator
url:            'http://haechi.me'
author:         'Alexander Zhou'
