name: 'Haechi'
description: 'When I let go of what I am, I become what I might be.'
meta_description: 'Morning Calm ...'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: /
domain_name: 'haechi.me'
google_analytics: 'UA-65232017-1'
plugins: [jekyll-paginate]


# Details for the RSS feed generator
url:            'http://haechi.me'
author:         'Alexander Zhou'
